# Generated by Django 2.1.7 on 2019-03-12 09:39

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
        ('address', '0002_auto_20160213_1726'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('instrument', models.ManyToManyField(to='instrument.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
