# Generated by Django 2.1.7 on 2019-03-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='price',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='price_currency',
        ),
    ]
