# Generated by Django 2.1.7 on 2019-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20190312_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='room',
        ),
    ]
