# Generated by Django 2.1.7 on 2019-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
        ('room', '0005_auto_20190312_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.AddField(
            model_name='room',
            name='instrument',
            field=models.ManyToManyField(to='instrument.Instrument'),
        ),
    ]
