# Generated by Django 2.1.7 on 2019-03-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190307_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='user_id',
            new_name='user',
        ),
    ]
