# Generated by Django 2.1.7 on 2019-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190307_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='verified_to_host',
            field=models.BooleanField(default=False),
        ),
    ]
