# Generated by Django 2.1.7 on 2019-03-08 08:15

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_host_verified_to_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_no', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcardnumber',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Host'),
        ),
    ]
