# Generated by Django 2.1.7 on 2019-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190308_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_to_host',
            field=models.BooleanField(default=False),
        ),
    ]
