# Generated by Django 2.1.7 on 2019-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
